fragment StudentParts on Student {
  title
  author
  date
  body
}

fragment TeacherParts on Teacher {
  title
  author
  date
  body
}

fragment ParentParts on Parent {
  title
  author
  date
  body
}
