fragment StudentParts on Student {
  title
  author {
    ... on Document {
      id
    }
  }
  date
  body
}

fragment TeacherParts on Teacher {
  title
  author {
    ... on Document {
      id
    }
  }
  date
  body
}

fragment ParentParts on Parent {
  title
  author {
    ... on Document {
      id
    }
  }
  date
  body
}

fragment AuthorsParts on Authors {
  name
  avatar
}
