query getStudentDocument($relativePath: String!) {
  getStudentDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...StudentParts
    }
  }
}

query getStudentList {
  getStudentList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...StudentParts
        }
      }
    }
  }
}

query getTeacherDocument($relativePath: String!) {
  getTeacherDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...TeacherParts
    }
  }
}

query getTeacherList {
  getTeacherList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...TeacherParts
        }
      }
    }
  }
}

query getParentDocument($relativePath: String!) {
  getParentDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...ParentParts
    }
  }
}

query getParentList {
  getParentList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...ParentParts
        }
      }
    }
  }
}

query getAuthorsDocument($relativePath: String!) {
  getAuthorsDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...AuthorsParts
    }
  }
}

query getAuthorsList {
  getAuthorsList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...AuthorsParts
        }
      }
    }
  }
}
