query student($relativePath: String!) {
  student(relativePath: $relativePath) {
    _sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    ...StudentParts
  }
}

query studentConnection {
  studentConnection {
    totalCount
    edges {
      node {
        id
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        ...StudentParts
      }
    }
  }
}

query teacher($relativePath: String!) {
  teacher(relativePath: $relativePath) {
    _sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    ...TeacherParts
  }
}

query teacherConnection {
  teacherConnection {
    totalCount
    edges {
      node {
        id
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        ...TeacherParts
      }
    }
  }
}

query parent($relativePath: String!) {
  parent(relativePath: $relativePath) {
    _sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    ...ParentParts
  }
}

query parentConnection {
  parentConnection {
    totalCount
    edges {
      node {
        id
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        ...ParentParts
      }
    }
  }
}
